# Generated by Django 4.2.11 on 2024-04-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolios.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolios.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolios.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolios.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='portfolios.profile'),
            preserve_default=False,
        ),
    ]
